export { default as Facebook } from './Facebook'
export { default as Tick } from './Tick'
export { default as Twitch } from './Twitch'
export { default as Twitter } from './Twitter'
export { default as Youtube } from './Youtube'